name: vip_conceptqa
channels:
  - defaults
  - pytorch
  - nvidia
dependencies:
  - pytorch-cuda=11.8
  - gpustat=0.6.0
  - matplotlib=3.8.0
  - numpy=1.26.2
  - pip=23.3.1
  - python=3.11
  - torchvision=0.16.1
  - rich=13.3.5
  - seaborn=0.12.2
  - typer=0.9.0
  - pip:
      - ftfy==6.1.3
      - git+https://github.com/openai/CLIP.git
      - polars==0.19.19
      - regex==2023.10.3
      - tqdm==4.65.0
